"use client"

import { useState } from "react"
import Image from "next/image"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export default function GrowthLab() {
  const [activeFilter, setActiveFilter] = useState("All Posts")

  const categories = ["All Posts", "Analytics", "GEO", "Performance"]

  const articles = [
    {
      id: 4,
      title: "The Ultimate Guide to LLM Brand Visibility & Generative Engine Optimization (GEO)",
      excerpt: "In 2026, the digital landscape for brands is transforming radically. The rise of generative AI-powered language models means brand visibility now hinges on new strategies. Discover Generative Engine Optimization (GEO).",
      category: "GEO",
      date: "March 11, 2026",
      image: "/posts/The Ultimate Guide to LLM Brand Visibility.webp",
      slug: "the-ultimate-guide-llm-brand-visibility-geo",
    },
    {
      id: 3,
      title: "The Ultimate Guide to Website Page Speed in 2026",
      excerpt:
        "Nobody purposely designs a slow website, but in today's attention economy, we are no longer fighting for minutes of user engagement, we are fighting for absolute milliseconds. In this guide, I show you how I achieved a flawless 100/100 Google PageSpeed score.",
      category: "Performance",
      date: "March 6, 2026",
      image: "/posts/thumbnail-futuristic-data-center.webp",
      slug: "website-page-speed-guide-2026",
    },
    {
      id: 1,
      title: "The 10 Best LLM Monitoring Tools for Brand Visibility in 2026",
      excerpt:
        "The SEO landscape has fundamentally transformed. We are no longer just fighting for ten blue links; today, the battleground is the single, definitive answer generated by Large Language Models. I ran a massive, live audit across the top AI visibility platforms to compare how they handle brand monitoring.",
      category: "GEO",
      date: "February 24, 2026",
      image: "/posts/thumbnail-10-ai-visibility-tools.webp",
      slug: "best-llm-monitoring-tools-brand-visibility",
    },
    {
      id: 2,
      title: "Web Analytics: The Guide to Implementation and Optimization",
      excerpt:
        "We live in a world where documenting that something happened often matters more than how it actually occurred in reality. A doctor's medical chart carries more weight than the actual treatment provided, because the next doctor will base their actions on that documented diagnosis and patient status. The same applies to police officers, lawyers, and accountants—their reports and documentation often matter more than the actual events.",
      category: "Analytics",
      date: "August 3, 2025",
      image: "/posts/google-analytics-focus-hero-image.webp?height=200&width=400&text=Web+Analytics",
      slug: "web-analytics-fundamentals",
    },
  ]

  const filteredArticles =
    activeFilter === "All Posts" ? articles : articles.filter((article) => article.category === activeFilter)

  return (
    <div className="min-h-screen py-20 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">Growth Lab: Experiments & Insights</h1>
          <p className="text-xl text-gray-300 max-w-3xl mx-auto">
            Deep dives into growth strategies, experiments, and insights from the trenches of digital marketing.
          </p>
        </div>

        {/* Filter Buttons */}
        <div className="flex flex-wrap justify-center gap-4 mb-12">
          {categories.map((category) => (
            <Button
              key={category}
              variant={activeFilter === category ? "default" : "outline"}
              onClick={() => setActiveFilter(category)}
              className={
                activeFilter === category
                  ? "bg-blue-500 hover:bg-blue-600 text-white"
                  : "border-gray-600 text-gray-300 hover:bg-gray-800"
              }
            >
              {category}
            </Button>
          ))}
        </div>

        {/* Articles Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {filteredArticles.map((article) => (
            <Link key={article.id} href={`/growth-lab/${article.slug}`}>
              <article className="bg-gray-800 rounded-lg overflow-hidden hover:bg-gray-750 transition-colors duration-200 cursor-pointer">
                <Image
                  src={article.image || "/placeholder.svg"}
                  alt={article.title}
                  width={400}
                  height={200}
                  className="w-full h-48 object-cover"
                />
                <div className="p-6">
                  <div className="flex items-center text-sm text-gray-400 mb-3">
                    <span className="bg-blue-500 text-white px-2 py-1 rounded text-xs mr-3">{article.category}</span>
                    <span>{article.date}</span>
                  </div>
                  <h3 className="text-xl font-semibold mb-3 line-clamp-2">{article.title}</h3>
                  <p className="text-gray-300 line-clamp-3">{article.excerpt}</p>
                </div>
              </article>
            </Link>
          ))}
        </div>
      </div>
    </div>
  )
}
