"use client"

import React, { useState, useCallback, useEffect } from "react"
import useEmblaCarousel from "embla-carousel-react"
import { ChevronLeft, ChevronRight } from "lucide-react"
import Image from "next/image"
import Link from "next/link"

const articles = [
    {
        id: 4,
        title: "The Ultimate Guide to LLM Brand Visibility & Generative Engine Optimization (GEO)",
        excerpt:
            "In 2026, the digital landscape for brands is transforming radically. The rise of generative AI-powered language models means brand visibility now hinges on new strategies. Discover Generative Engine Optimization (GEO).",
        category: "GEO",
        date: "March 11, 2026",
        image: "/posts/The Ultimate Guide to LLM Brand Visibility.webp",
        slug: "the-ultimate-guide-llm-brand-visibility-geo",
    },
    {
        id: 3,
        title: "The Ultimate Guide to Website Page Speed in 2026",
        excerpt:
            "Nobody purposely designs a slow website, but in today's attention economy, we are no longer fighting for minutes of user engagement, we are fighting for absolute milliseconds. In this guide, I show you how I achieved a flawless 100/100 Google PageSpeed score.",
        category: "Performance",
        date: "March 6, 2026",
        image: "/posts/thumbnail-futuristic-data-center.webp",
        slug: "website-page-speed-guide-2026",
    },
    {
        id: 1,
        title: "The 10 Best LLM Monitoring Tools for Brand Visibility in 2026",
        excerpt:
            "The SEO landscape has fundamentally transformed. We are no longer just fighting for ten blue links; today, the battleground is the single, definitive answer generated by Large Language Models. I ran a massive, live audit across the top AI visibility platforms to compare how they handle brand monitoring.",
        category: "GEO",
        date: "February 24, 2026",
        image: "/posts/thumbnail-10-ai-visibility-tools.webp",
        slug: "best-llm-monitoring-tools-brand-visibility",
    },
    {
        id: 2,
        title: "Web Analytics: The Guide to Implementation and Optimization",
        excerpt:
            "We live in a world where documenting that something happened often matters more than how it actually occurred in reality. A doctor's medical chart carries more weight than the actual treatment provided, because the next doctor will base their actions on that documented diagnosis and patient status. The same applies to police officers, lawyers, and accountants—their reports and documentation often matter more than the actual events.",
        category: "Analytics",
        date: "August 3, 2025",
        image: "/posts/google-analytics-focus-hero-image.webp?height=200&width=400&text=Web+Analytics",
        slug: "web-analytics-fundamentals",
    },
]

export default function LatestExperimentsCarousel() {
    const [emblaRef, emblaApi] = useEmblaCarousel({ align: "start", loop: false })
    const [canScrollPrev, setCanScrollPrev] = useState(false)
    const [canScrollNext, setCanScrollNext] = useState(false)

    const scrollPrev = useCallback(() => emblaApi && emblaApi.scrollPrev(), [emblaApi])
    const scrollNext = useCallback(() => emblaApi && emblaApi.scrollNext(), [emblaApi])

    const onSelect = useCallback(() => {
        if (!emblaApi) return
        setCanScrollPrev(emblaApi.canScrollPrev())
        setCanScrollNext(emblaApi.canScrollNext())
    }, [emblaApi])

    useEffect(() => {
        if (!emblaApi) return
        onSelect()
        emblaApi.on("select", onSelect)
        emblaApi.on("reInit", onSelect)
    }, [emblaApi, onSelect])

    return (
        <section className="py-20 px-4 sm:px-6 lg:px-8">
            <div className="max-w-7xl mx-auto">
                <h2 className="text-4xl md:text-5xl font-bold mb-12 text-center text-white">Latest growth experiments</h2>

                <div className="relative w-full">
                    {/* Navigation Arrows */}
                    <button
                        onClick={scrollPrev}
                        disabled={!canScrollPrev}
                        className={`absolute -left-4 md:-left-6 top-1/2 -translate-y-1/2 z-10 w-12 h-12 bg-gray-800 hover:bg-gray-700 rounded-full flex items-center justify-center transition-colors duration-200 border border-gray-600 ${!canScrollPrev ? "opacity-50 cursor-not-allowed" : ""
                            }`}
                        aria-label="Previous posts"
                    >
                        <ChevronLeft className="w-6 h-6 text-white" />
                    </button>

                    <button
                        onClick={scrollNext}
                        disabled={!canScrollNext}
                        className={`absolute -right-4 md:-right-6 top-1/2 -translate-y-1/2 z-10 w-12 h-12 bg-gray-800 hover:bg-gray-700 rounded-full flex items-center justify-center transition-colors duration-200 border border-gray-600 ${!canScrollNext ? "opacity-50 cursor-not-allowed" : ""
                            }`}
                        aria-label="Next posts"
                    >
                        <ChevronRight className="w-6 h-6 text-white" />
                    </button>

                    {/* Carousel */}
                    <div className="overflow-hidden" ref={emblaRef}>
                        <div className="flex -ml-6">
                            {articles.map((article) => (
                                <div key={article.id} className="flex-[0_0_100%] min-w-0 pl-6 md:flex-[0_0_50%] lg:flex-[0_0_33.333333%]">
                                    <Link href={`/growth-lab/${article.slug}`}>
                                        <article className="bg-[#1A1A1A] border border-gray-800 rounded-lg overflow-hidden hover:bg-gray-800/80 transition-all duration-300 hover:border-cyan-500/30 cursor-pointer h-full flex flex-col group">
                                            <div className="relative w-full h-48 overflow-hidden">
                                                <Image
                                                    src={article.image || "/placeholder.svg"}
                                                    alt={article.title}
                                                    width={400}
                                                    height={200}
                                                    className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                                                />
                                            </div>
                                            <div className="p-6 flex-1 flex flex-col">
                                                <div className="flex items-center text-sm text-gray-400 mb-4">
                                                    <span className="bg-blue-500 text-white font-medium px-2.5 py-1 rounded text-xs mr-3">{article.category}</span>
                                                    <span className="text-gray-400 text-sm">{article.date}</span>
                                                </div>
                                                <h3 className="text-xl font-bold mb-3 text-white line-clamp-2 leading-snug group-hover:text-cyan-400 transition-colors duration-200">{article.title}</h3>
                                                <p className="text-gray-400 line-clamp-3 text-sm leading-relaxed">{article.excerpt}</p>
                                            </div>
                                        </article>
                                    </Link>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    )
}
