export interface Article {
  id: number
  title: string
  excerpt: string
  category: string
  date: string
  image: string
  slug: string
}

export const articles: Article[] = [
  {
    id: 7,
    title: "How to Run an LLM Brand Visibility Audit (Enterprise Framework)",
    excerpt:
      "Your SEO team just showed you a dashboard where everything is green. Rankings holding, technical health at 88, Core Web Vitals passing. Meanwhile ChatGPT, Gemini, and Perplexity are recommending your competitor by name and skipping you entirely. Here is the enterprise framework to audit and fix your LLM visibility.",
    category: "GEO",
    date: "June 25, 2026",
    image: "/posts/llm-brand-visibility-audit.webp",
    slug: "how-to-run-an-llm-brand-visibility-audit",
  },
  {
    id: 6,
    title: "How I Use n8n to Automate SEO, Newsletters, and Link Building (Full Breakdown)",
    excerpt:
      "Building your own automation infrastructure might sound like overkill, but the strategic advantage is massive. Here is a full breakdown of three heavily relied-upon workflows running on my self-hosted n8n server, and the business logic that makes them so powerful.",
    category: "Automation",
    date: "May 29, 2026",
    image: "/posts/n8n-automation.webp",
    slug: "how-i-use-n8n-to-automate-seo-newsletters-and-link-building",
  },
  {
    id: 5,
    title: "Where Does ChatGPT Get Its Information? Inside 143,010 Citations From UK Banking Conversations",
    excerpt:
      "Across 25,417 simulated ChatGPT conversations about UK retail and commercial banking in 2026, the model cited 143,010 sources, drawn from 4,125 distinct domains. Only 2.57% of those citations pointed to a bank's own website. The other 97.43% came from places most banks have never optimized for, and in many cases have never even audited.",
    category: "GEO",
    date: "May 28, 2026",
    image: "/posts/where-does-chatgpt-get-its-information.webp",
    slug: "where-does-chatgpt-get-its-information",
  },
  {
    id: 4,
    title: "The Ultimate Guide to LLM Brand Visibility & Generative Engine Optimization (GEO)",
    excerpt:
      "In 2026, the digital landscape for brands is transforming radically. The rise of generative AI-powered language models means brand visibility now hinges on new strategies. Discover Generative Engine Optimization (GEO).",
    category: "GEO",
    date: "March 11, 2026",
    image: "/posts/The Ultimate Guide to LLM Brand Visibility.webp",
    slug: "the-ultimate-guide-llm-brand-visibility-geo",
  },
  {
    id: 3,
    title: "The Ultimate Guide to Website Page Speed in 2026",
    excerpt:
      "Nobody purposely designs a slow website, but in today's attention economy, we are no longer fighting for minutes of user engagement, we are fighting for absolute milliseconds. In this guide, I show you how I achieved a flawless 100/100 Google PageSpeed score.",
    category: "Performance",
    date: "March 6, 2026",
    image: "/posts/thumbnail-futuristic-data-center.webp",
    slug: "website-page-speed-guide-2026",
  },
  {
    id: 1,
    title: "The 10 Best LLM Monitoring Tools for Brand Visibility in 2026",
    excerpt:
      "The SEO landscape has fundamentally transformed. We are no longer just fighting for ten blue links; today, the battleground is the single, definitive answer generated by Large Language Models. I ran a massive, live audit across the top AI visibility platforms to compare how they handle brand monitoring.",
    category: "GEO",
    date: "February 24, 2026",
    image: "/posts/thumbnail-10-ai-visibility-tools.webp",
    slug: "best-llm-monitoring-tools-brand-visibility",
  },
  {
    id: 2,
    title: "Web Analytics: The Guide to Implementation and Optimization",
    excerpt:
      "We live in a world where documenting that something happened often matters more than how it occurred in reality. A doctor's medical chart carries more weight than the actual treatment provided, because the next doctor will base their actions on that documented diagnosis and patient status. The same applies to police officers, lawyers, and accountants—their reports and documentation often matter more than the actual events.",
    category: "Analytics",
    date: "August 3, 2025",
    image: "/posts/google-analytics-focus-hero-image.webp?height=200&width=400&text=Web+Analytics",
    slug: "web-analytics-fundamentals",
  },
]
